import { Poppins } from 'next/font/google';
import { ReactNode } from 'react';
import Header from 'components/header';
import 'styles/globals.css';

import MuiProvider from 'providers/MuiProvider';

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '500', '600', '700'] });

export const metadata = {
	title: 'Checkout App',
	description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: ReactNode }) => {
	return (
		<html lang='en'>
			<MuiProvider>
				<body className={poppins.className} suppressHydrationWarning={true}>
					<Header />
					{children}
				</body>
			</MuiProvider>
		</html>
	);
};

export default RootLayout;
